server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhonghuan?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    filters: stat
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 6000
  resources:
    static-locations: classpath:/static/, classpath:/templates/

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.zhonghuan.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
